require('dotenv').config({ path: './.env' });
const mongoose = require('mongoose');

const Patient = require('../models/Patient');
const User = require('../models/User');
const Consultation = require('../models/Consultation');
const TreatmentRecord = require('../models/TreatmentRecord');
const Invoice = require('../models/Invoice');
require('../models/Diagnosis');

const { listInvoices } = require('../controllers/invoiceController');

async function verifyPendingBillsTab() {
  try {
    const uri = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/dental-clinic';
    await mongoose.connect(uri);
    console.log('=== STARTING PENDING BILLS SECTION VERIFICATION ===\n');

    let doctor = await User.findOne({ role: 'doctor' });
    if (!doctor) {
      doctor = await User.create({
        name: 'Dr. Billing Specialist',
        email: `dr.billing.${Date.now()}@clinic.com`,
        password: 'Password123!',
        role: 'doctor',
      });
    }

    const patient = await Patient.create({
      firstName: 'PendingBill',
      lastName: 'TestUser',
      opNumber: `OP-BILL-${Date.now().toString().slice(-4)}`,
      phone: '9555544444',
      age: 40,
      sex: 'Female',
    });

    const consultation = await Consultation.create({
      patient: patient._id,
      doctor: doctor._id,
      status: 'Completed',
    });

    // Create 2 performed treatment records
    await TreatmentRecord.create([
      {
        consultation: consultation._id,
        patient: patient._id,
        tooth: 15,
        procedure: 'Ceramic Crown Placement',
        charges: 8000,
      },
      {
        consultation: consultation._id,
        patient: patient._id,
        tooth: 15,
        procedure: 'Gingival Scaling',
        charges: 1500,
      },
    ]);

    // Create Pending Invoice generated by doctor closing consultation
    const invoice = await Invoice.create({
      patient: patient._id,
      doctor: doctor._id,
      consultation: consultation._id,
      opNumber: patient.opNumber,
      items: [
        { service: 'Ceramic Crown Placement (Tooth #15)', treatment: 'Ceramic Crown Placement', quantity: 1, unitPrice: 8000 },
        { service: 'Gingival Scaling (Tooth #15)', treatment: 'Gingival Scaling', quantity: 1, unitPrice: 1500 },
      ],
      paymentStatus: 'Pending',
    });

    console.log(`Created test pending bill (ID: ${invoice._id}, total: ₹${invoice.total})`);

    // 1. Query pending bills endpoint (status=Pending)
    console.log('\n1. Querying GET /api/invoices?status=Pending...');
    let result = null;
    const reqMock = {
      query: { status: 'Pending', search: patient.firstName },
    };
    const resMock = {
      json: (data) => { result = data; },
    };

    await listInvoices(reqMock, resMock, (err) => { throw err; });

    console.log(`   Found Pending Invoices: ${result.invoices.length}`);

    if (result.invoices.length === 0) {
      throw new Error('FAIL: Created pending bill was not returned in search results!');
    }

    const foundInv = result.invoices.find((i) => i._id.toString() === invoice._id.toString());
    if (!foundInv) {
      throw new Error('FAIL: Target pending bill was not found in filtered results!');
    }

    console.log('   Checking required fields for Pending Bills table columns:');
    console.log(`   - Patient Name: ${foundInv.patient?.firstName} ${foundInv.patient?.lastName}`);
    console.log(`   - OP Number: ${foundInv.opNumber || foundInv.patient?.opNumber}`);
    console.log(`   - Doctor Name: Dr. ${foundInv.doctor?.name}`);
    console.log(`   - Visit Date: ${foundInv.createdAt}`);
    console.log(`   - Procedures Count: ${foundInv.items?.length}`);
    console.log(`   - Amount Due (Balance): ₹${foundInv.balance}`);
    console.log(`   - Payment Status: ${foundInv.paymentStatus}`);

    if (!foundInv.patient || !foundInv.doctor || !foundInv.items || foundInv.balance !== 9500) {
      throw new Error('FAIL: Required table column fields missing or incorrect balance');
    }
    console.log('   Pending Bills Table Column Requirements: PASSED ✓');

    // 2. Query doctor filter
    console.log('\n2. Testing Doctor Filter (doctor=...)');
    let docFilterResult = null;
    await listInvoices({ query: { status: 'Pending', doctor: doctor._id } }, { json: (d) => { docFilterResult = d; } }, (e) => { throw e; });

    console.log(`   Doctor Filter matched: ${docFilterResult.invoices.length} invoices`);
    if (docFilterResult.invoices.length === 0) {
      throw new Error('FAIL: Doctor filter returned 0 results!');
    }
    console.log('   Doctor Filter: PASSED ✓');

    // Clean up test documents
    console.log('\n3. Cleaning up test records...');
    await TreatmentRecord.deleteMany({ consultation: consultation._id });
    await Invoice.deleteMany({ consultation: consultation._id });
    await Consultation.deleteOne({ _id: consultation._id });
    await Patient.deleteOne({ _id: patient._id });
    console.log('   Cleanup done.');

    console.log('\n=== ALL PENDING BILLS TAB TESTS PASSED PERFECTLY ===\n');
    await mongoose.disconnect();
    process.exit(0);
  } catch (err) {
    console.error('\n❌ VERIFICATION FAILED:', err);
    await mongoose.disconnect();
    process.exit(1);
  }
}

verifyPendingBillsTab();
