const ExcelJS = require('exceljs');

const BRAND_TEAL = '0E7C7B';
const HEADER_FONT_COLOR = 'FFFFFF';
const EVEN_ROW_BG = 'F8FAFC';
const SUMMARY_HEADER_BG = 'E2E8F0';

function formatExcelDate(d) {
  if (!d) return null;
  const dateObj = new Date(d);
  return isNaN(dateObj.getTime()) ? null : dateObj;
}

function autoFitColumns(worksheet, minWidth = 12, maxWidth = 45) {
  worksheet.columns.forEach((column) => {
    let maxLen = column.header ? String(column.header).length : minWidth;
    column.eachCell({ includeEmpty: true }, (cell) => {
      if (cell.value) {
        let cellLen = 0;
        if (cell.value instanceof Date) {
          cellLen = 12;
        } else if (typeof cell.value === 'object') {
          cellLen = JSON.stringify(cell.value).length;
        } else {
          cellLen = String(cell.value).length;
        }
        if (cellLen > maxLen) {
          maxLen = cellLen;
        }
      }
    });
    column.width = Math.min(maxWidth, Math.max(minWidth, maxLen + 3));
  });
}

function styleDataSheet(worksheet, columnDefs) {
  // Freeze header row
  worksheet.views = [{ state: 'frozen', ySplit: 1 }];

  // Style header row (Row 1)
  const headerRow = worksheet.getRow(1);
  headerRow.height = 26;
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: HEADER_FONT_COLOR }, size: 11, name: 'Segoe UI' };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: BRAND_TEAL },
    };
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
  });

  // Enable AutoFilter
  worksheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: columnDefs.length },
  };

  // Alternating row shading & border formatting
  worksheet.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return;
    row.height = 20;

    const isEven = rowNumber % 2 === 0;
    row.eachCell({ includeEmpty: true }, (cell, colNumber) => {
      cell.font = { size: 10, name: 'Segoe UI' };
      if (isEven) {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: EVEN_ROW_BG },
        };
      }

      // Column formatting from columnDefs
      const colDef = columnDefs[colNumber - 1];
      if (colDef) {
        if (colDef.numFmt) {
          cell.numFmt = colDef.numFmt;
        }
        if (colDef.align) {
          cell.alignment = { vertical: 'middle', horizontal: colDef.align };
        } else {
          cell.alignment = { vertical: 'middle', horizontal: 'left' };
        }
      }
    });
  });

  autoFitColumns(worksheet);
}

async function generateBackupWorkbook(data, adminUser) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = adminUser?.name || 'Admin';
  workbook.created = new Date();

  const clinicName = data.settings?.clinicName || 'Dental Care Clinic';
  const currencySymbol = data.settings?.currency === 'INR' ? '₹' : (data.settings?.currency || '₹');
  const currencyNumFmt = `"${currencySymbol}"#,##0.00`;
  const dateNumFmt = 'dd mmm yyyy';

  // -------------------------------------------------------------
  // 1. COVER SHEET ("Summary")
  // -------------------------------------------------------------
  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.views = [{ state: 'frozen', ySplit: 0 }];

  summarySheet.getCell('A1').value = clinicName;
  summarySheet.getCell('A1').font = { size: 16, bold: true, color: { argb: '0F172A' }, name: 'Segoe UI' };

  summarySheet.getCell('A2').value = 'Official Clinic Backup & Operational Snapshot';
  summarySheet.getCell('A2').font = { size: 11, italic: true, color: { argb: '64748B' }, name: 'Segoe UI' };

  summarySheet.getCell('A4').value = 'Export Generated:';
  summarySheet.getCell('A4').font = { bold: true, size: 10, name: 'Segoe UI' };
  summarySheet.getCell('B4').value = new Date().toLocaleString();
  summarySheet.getCell('B4').font = { size: 10, name: 'Segoe UI' };

  summarySheet.getCell('A5').value = 'Generated By:';
  summarySheet.getCell('A5').font = { bold: true, size: 10, name: 'Segoe UI' };
  summarySheet.getCell('B5').value = adminUser?.name ? `${adminUser.name} (${adminUser.email || 'Admin'})` : 'System Administrator';
  summarySheet.getCell('B5').font = { size: 10, name: 'Segoe UI' };

  summarySheet.getCell('A7').value = 'Collections Summary';
  summarySheet.getCell('A7').font = { size: 13, bold: true, color: { argb: '0F172A' }, name: 'Segoe UI' };

  // Summary Table Header
  const summaryHeaderRow = summarySheet.getRow(8);
  summaryHeaderRow.getCell(1).value = 'Data Sheet Name';
  summaryHeaderRow.getCell(2).value = 'Record Count';
  summaryHeaderRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: '0F172A' }, size: 10, name: 'Segoe UI' };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUMMARY_HEADER_BG } };
  });

  const sheetCounts = [
    { name: 'Patients', count: (data.patients || []).length },
    { name: 'Appointments', count: (data.appointments || []).length },
    { name: 'Invoices', count: (data.invoices || []).length },
    { name: 'TreatmentPlans', count: (data.treatmentPlans || []).length },
    { name: 'Consultations', count: (data.consultations || []).length },
    { name: 'Diagnoses', count: (data.diagnoses || []).length },
    { name: 'Prescriptions', count: (data.prescriptions || []).length },
    { name: 'FollowUps', count: (data.followUps || []).length },
  ];

  sheetCounts.forEach((sc, idx) => {
    const row = summarySheet.getRow(9 + idx);
    row.getCell(1).value = sc.name;
    row.getCell(1).font = { size: 10, name: 'Segoe UI' };
    row.getCell(2).value = sc.count;
    row.getCell(2).font = { size: 10, name: 'Segoe UI' };
    row.getCell(2).alignment = { horizontal: 'right' };
  });

  autoFitColumns(summarySheet, 15, 40);

  // -------------------------------------------------------------
  // 2. PATIENTS SHEET
  // -------------------------------------------------------------
  const patientsSheet = workbook.addWorksheet('Patients');
  const patientColDefs = [
    { header: 'OP Number', key: 'opNumber' },
    { header: 'Patient Name', key: 'name' },
    { header: 'Age', key: 'age', align: 'right' },
    { header: 'Sex', key: 'sex' },
    { header: 'Phone', key: 'phone' },
    { header: 'Address', key: 'address' },
    { header: 'Registration Date', key: 'registrationDate', numFmt: dateNumFmt },
    { header: 'Medical History', key: 'medicalHistory' },
    { header: 'Habits', key: 'habits' },
    { header: 'Dental History', key: 'dentalHistory' },
  ];
  patientsSheet.columns = patientColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.patients || []).forEach((p) => {
    patientsSheet.addRow({
      opNumber: p.opNumber || '—',
      name: `${p.firstName || ''} ${p.lastName || ''}`.trim() || 'Unnamed',
      age: p.age ?? '',
      sex: p.sex || '',
      phone: p.phone || '',
      address: p.address || '',
      registrationDate: formatExcelDate(p.registrationDate || p.createdAt),
      medicalHistory: Array.isArray(p.medicalHistory) ? p.medicalHistory.join(', ') : (p.medicalHistory || ''),
      habits: Array.isArray(p.habits) ? p.habits.join(', ') : (p.habits || ''),
      dentalHistory: p.dentalHistory || '',
    });
  });
  styleDataSheet(patientsSheet, patientColDefs);

  // -------------------------------------------------------------
  // 3. APPOINTMENTS SHEET
  // -------------------------------------------------------------
  const appointmentsSheet = workbook.addWorksheet('Appointments');
  const aptColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Doctor Name', key: 'doctorName' },
    { header: 'Date', key: 'date', numFmt: dateNumFmt },
    { header: 'Time', key: 'time' },
    { header: 'Reason', key: 'reason' },
    { header: 'Status', key: 'status' },
    { header: 'Type', key: 'type' },
  ];
  appointmentsSheet.columns = aptColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.appointments || []).forEach((a) => {
    const pName = a.patient ? `${a.patient.firstName || ''} ${a.patient.lastName || ''}`.trim() : 'Unknown Patient';
    const dName = a.doctor ? `Dr. ${a.doctor.name}` : 'Unassigned';

    appointmentsSheet.addRow({
      patientName: pName,
      doctorName: dName,
      date: formatExcelDate(a.date),
      time: a.time || '',
      reason: a.reason || '',
      status: a.status || '',
      type: a.type || 'Appointment',
    });
  });
  styleDataSheet(appointmentsSheet, aptColDefs);

  // -------------------------------------------------------------
  // 4. INVOICES SHEET
  // -------------------------------------------------------------
  const invoicesSheet = workbook.addWorksheet('Invoices');
  const invColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Doctor Name', key: 'doctorName' },
    { header: 'OP Number', key: 'opNumber' },
    { header: 'Itemized Services', key: 'services' },
    { header: 'Discount', key: 'discount', numFmt: currencyNumFmt, align: 'right' },
    { header: 'Tax', key: 'tax', numFmt: currencyNumFmt, align: 'right' },
    { header: 'Total Amount', key: 'total', numFmt: currencyNumFmt, align: 'right' },
    { header: 'Amount Paid', key: 'amountPaid', numFmt: currencyNumFmt, align: 'right' },
    { header: 'Balance Dues', key: 'balance', numFmt: currencyNumFmt, align: 'right' },
    { header: 'Payment Status', key: 'paymentStatus' },
  ];
  invoicesSheet.columns = invColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.invoices || []).forEach((inv) => {
    const pName = inv.patient ? `${inv.patient.firstName || ''} ${inv.patient.lastName || ''}`.trim() : 'Unknown Patient';
    const dName = inv.doctor ? `Dr. ${inv.doctor.name}` : 'Unassigned';

    const itemStr = (inv.items || [])
      .map((i) => `${i.service || i.treatment || 'Procedure'} x${i.quantity || 1} @ ${currencySymbol}${i.unitPrice || 0}`)
      .join('; ');

    invoicesSheet.addRow({
      patientName: pName,
      doctorName: dName,
      opNumber: inv.opNumber || '',
      services: itemStr || '—',
      discount: inv.discount || 0,
      tax: inv.tax || 0,
      total: inv.total || 0,
      amountPaid: inv.amountPaid || 0,
      balance: inv.balance || 0,
      paymentStatus: inv.paymentStatus || 'Pending',
    });
  });
  styleDataSheet(invoicesSheet, invColDefs);

  // -------------------------------------------------------------
  // 5. TREATMENT PLANS SHEET
  // -------------------------------------------------------------
  const plansSheet = workbook.addWorksheet('TreatmentPlans');
  const planColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Tooth FDI', key: 'tooth', align: 'center' },
    { header: 'Treatment', key: 'treatment' },
    { header: 'Estimated Cost', key: 'estimatedCost', numFmt: currencyNumFmt, align: 'right' },
    { header: 'Priority', key: 'priority' },
    { header: 'Status', key: 'status' },
    { header: 'Notes', key: 'notes' },
  ];
  plansSheet.columns = planColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.treatmentPlans || []).forEach((tp) => {
    const pName = tp.patient ? `${tp.patient.firstName || ''} ${tp.patient.lastName || ''}`.trim() : 'Unknown Patient';

    plansSheet.addRow({
      patientName: pName,
      tooth: tp.tooth ? `#${tp.tooth}` : '—',
      treatment: tp.treatment || '',
      estimatedCost: tp.estimatedCost || 0,
      priority: tp.priority || 'Medium',
      status: tp.status || 'Planned',
      notes: tp.notes || '',
    });
  });
  styleDataSheet(plansSheet, planColDefs);

  // -------------------------------------------------------------
  // 6. CONSULTATIONS SHEET
  // -------------------------------------------------------------
  const consultationsSheet = workbook.addWorksheet('Consultations');
  const consultColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Doctor Name', key: 'doctorName' },
    { header: 'Status', key: 'status' },
    { header: 'Started At', key: 'startedAt', numFmt: dateNumFmt },
    { header: 'Closed At', key: 'closedAt', numFmt: dateNumFmt },
  ];
  consultationsSheet.columns = consultColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.consultations || []).forEach((c) => {
    const pName = c.patient ? `${c.patient.firstName || ''} ${c.patient.lastName || ''}`.trim() : 'Unknown Patient';
    const dName = c.doctor ? `Dr. ${c.doctor.name}` : 'Unassigned';

    consultationsSheet.addRow({
      patientName: pName,
      doctorName: dName,
      status: c.status || 'In Progress',
      startedAt: formatExcelDate(c.startedAt || c.createdAt),
      closedAt: formatExcelDate(c.closedAt),
    });
  });
  styleDataSheet(consultationsSheet, consultColDefs);

  // -------------------------------------------------------------
  // 7. DIAGNOSES SHEET
  // -------------------------------------------------------------
  const diagnosesSheet = workbook.addWorksheet('Diagnoses');
  const diagColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Diagnosis', key: 'diagnosis' },
    { header: 'Related Teeth', key: 'relatedTeeth' },
    { header: 'Severity', key: 'severity' },
    { header: 'Notes', key: 'notes' },
    { header: 'Recorded Date', key: 'recordedAt', numFmt: dateNumFmt },
  ];
  diagnosesSheet.columns = diagColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.diagnoses || []).forEach((d) => {
    const pName = d.patient ? `${d.patient.firstName || ''} ${d.patient.lastName || ''}`.trim() : 'Unknown Patient';
    const teethStr = Array.isArray(d.relatedTeeth) ? d.relatedTeeth.map((t) => `#${t}`).join(', ') : '';

    diagnosesSheet.addRow({
      patientName: pName,
      diagnosis: d.diagnosis || '',
      relatedTeeth: teethStr || '—',
      severity: d.severity || 'Moderate',
      notes: d.notes || '',
      recordedAt: formatExcelDate(d.recordedAt || d.createdAt),
    });
  });
  styleDataSheet(diagnosesSheet, diagColDefs);

  // -------------------------------------------------------------
  // 8. PRESCRIPTIONS SHEET
  // -------------------------------------------------------------
  const prescriptionsSheet = workbook.addWorksheet('Prescriptions');
  const rxColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Medicines List', key: 'medicines' },
  ];
  prescriptionsSheet.columns = rxColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.prescriptions || []).forEach((rx) => {
    const pName = rx.patient ? `${rx.patient.firstName || ''} ${rx.patient.lastName || ''}`.trim() : 'Unknown Patient';

    const medStr = (rx.medicines || [])
      .map((m) => {
        const parts = [m.medicine, m.dosage, m.frequency, m.duration, m.instructions].filter(Boolean);
        return parts.join(' - ');
      })
      .join('\n');

    prescriptionsSheet.addRow({
      patientName: pName,
      medicines: medStr || '—',
    });
  });
  styleDataSheet(prescriptionsSheet, rxColDefs);

  // -------------------------------------------------------------
  // 9. FOLLOWUPS SHEET
  // -------------------------------------------------------------
  const followUpsSheet = workbook.addWorksheet('FollowUps');
  const fuColDefs = [
    { header: 'Patient Name', key: 'patientName' },
    { header: 'Recommended Date', key: 'recommendedDate', numFmt: dateNumFmt },
    { header: 'Reason', key: 'reason' },
    { header: 'Status', key: 'status' },
  ];
  followUpsSheet.columns = fuColDefs.map((c) => ({ header: c.header, key: c.key }));

  (data.followUps || []).forEach((fu) => {
    const pName = fu.patient ? `${fu.patient.firstName || ''} ${fu.patient.lastName || ''}`.trim() : 'Unknown Patient';

    followUpsSheet.addRow({
      patientName: pName,
      recommendedDate: formatExcelDate(fu.recommendedDate),
      reason: fu.reason || '',
      status: fu.status || 'Pending',
    });
  });
  styleDataSheet(followUpsSheet, fuColDefs);

  return workbook;
}

module.exports = {
  generateBackupWorkbook,
};
